// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkbGU5V6hc9gHEcvEOT9kxTqLfilPbR4Q',
    appId: '1:381218661910:web:d141d619dfa74df344b737',
    messagingSenderId: '381218661910',
    projectId: 'product-management-cart-app',
    authDomain: 'product-management-cart-app.firebaseapp.com',
    storageBucket: 'product-management-cart-app.firebasestorage.app',
    measurementId: 'G-4JZNQ11371',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgLI_amihkcXixAjKWH2_MqrUBGMHXMGU',
    appId: '1:381218661910:android:d1a2858d3a71e2e044b737',
    messagingSenderId: '381218661910',
    projectId: 'product-management-cart-app',
    storageBucket: 'product-management-cart-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkbGU5V6hc9gHEcvEOT9kxTqLfilPbR4Q',
    appId: '1:381218661910:web:50d8570d201863b144b737',
    messagingSenderId: '381218661910',
    projectId: 'product-management-cart-app',
    authDomain: 'product-management-cart-app.firebaseapp.com',
    storageBucket: 'product-management-cart-app.firebasestorage.app',
    measurementId: 'G-R3B63Y7Q9L',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiEe6yLu8zOu1og7IQfvoGRWz8pPZNno8',
    appId: '1:381218661910:ios:9ca169ce647559a444b737',
    messagingSenderId: '381218661910',
    projectId: 'product-management-cart-app',
    storageBucket: 'product-management-cart-app.firebasestorage.app',
    iosClientId:
        '381218661910-vmf0u414au8t5b4qr620t9gfp9ml5t57.apps.googleusercontent.com',
    iosBundleId: 'com.example.productManagementCartApp',
  );
}
